title: Hua-Yang Wang's Homepage
page-top-title: Hua-Yang Wang
top-section-bg-text: Fret not over bygones and the forward journey take
home-subtitle: Hua-Yang Wang&ensp;|&ensp;汪华洋
copyright-text: '&copy; Hua-Yang Wang 2022-2025. All Rights Reserved.'
